export const state = {
    httpRequest: false,
    dataList: [],
    authUser: false,
    software: '',
    filter: {
        per_page : 2,
        status : '',
    },
    Config: [],
    Permissions: [],
    isConfigLoaded: false,
    requiredData: [],
    formType: 1,
    updateId: '',
    formObject : {},
    formFilter : {
        perPage : 10,
        status : '',
    },
    modalTitle :'',
    currentPage :'',
    Notifications : [],
    NotificationIds : [],
    DesktopNotifications : [],
    DesktopNotificationIds : [],
    Messages : [],
    currentPagination : 1,
};
